import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {Readable} from 'node:stream';
import {createHandler} from '../02-hub/modules/signal/index.mjs';
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'hermes-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));let now=200000000;const file=path.join(root,'signal.json'),feed=path.join(root,'feed.json'),authFile=path.join(root,'auth.json');fs.writeFileSync(authFile,JSON.stringify({username:'admin',salt:'a',hash:'b'}));const handler=createHandler({file,feed,authFile,publicFile:path.join(root,'public.json'),now:()=>now});return {root,file,feed,authFile,handler,time:()=>now,advance:()=>now+=40000,events:(items,updatedAt=now)=>fs.writeFileSync(feed,JSON.stringify({updatedAt,events:items,active:[],devices:[]}))};}
const request=(input,token,headers={})=>{const r=Readable.from([Buffer.from(JSON.stringify(input))]);r.method='POST';r.headers={'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{}),...headers};return r;};
const call=(f,route,input)=>f.handler({request:request(input),path:route});
const phone=(f,token,input,headers)=>f.handler.publicHandle({request:request(input,token,headers)});
const create=async f=>(await call(f,'/phone/create',{name:'Телефон'})).json();
const event=(f,id,extra={})=>({id,time:f.time(),category:'services',level:'warning',title:'Служба',body:'Проверить',key:'service.hub',...extra});
test('Hermes keys are separate, hashed, revocable and invalidated by auth identity changes',async t=>{const f=fixture(t),d=await create(f);assert.equal(d.token.length,43);assert.ok(!fs.readFileSync(f.file,'utf8').includes(d.token));assert.equal((await phone(f,'bad',{type:'hello'})).status,401);assert.equal((await phone(f,d.token,{type:'hello'},{origin:'https://evil.test'})).status,401);assert.equal((await phone(f,d.token,{type:'hello'})).status,200);const list=await(await f.handler({request:{method:'GET'},path:'/phone'})).json();assert.ok(!JSON.stringify(list).includes('secret'));await call(f,'/phone/revoke',{id:d.id});assert.equal((await phone(f,d.token,{type:'hello'})).status,401);const fresh=await create(f);fs.writeFileSync(f.authFile,'{"username":"other"}');assert.equal((await phone(f,fresh.token,{type:'hello'})).status,401);});
test('Hermes filters old and disabled events, isolates device tests, paginates and handles read idempotently',async t=>{const f=fixture(t),one=await create(f),two=await create(f);f.events([event(f,'old',{time:f.time()-1}),event(f,'bad category',{category:'services'}),event(f,'disabled',{category:'unknown'}),...Array.from({length:25},(_,i)=>event(f,'event-'+String(i).padStart(2,'0')))]);let response=await(await phone(f,one.token,{type:'poll',seen:[]})).json();assert.equal(response.items.length,20);assert.equal(response.more,true);assert.equal(response.details,false);assert.equal(response.items[0].id,'event-00');const seen=response.items.map(e=>e.id);response=await(await phone(f,one.token,{type:'poll',seen})).json();assert.equal(response.items.length,5);assert.equal(response.more,false);for(let i=0;i<2;i++)assert.equal((await phone(f,one.token,{type:'read',id:'event-00'})).status,200);assert.equal((await phone(f,one.token,{type:'read',id:'not-in-feed'})).status,404);assert.equal((await(await phone(f,one.token,{type:'poll',seen:[]})).json()).items[0].id,'event-01');assert.equal((await(await phone(f,two.token,{type:'poll',seen:[]})).json()).items[0].id,'event-00');await call(f,'/phone/test',{id:one.id});f.events([]);assert.equal((await(await phone(f,one.token,{type:'poll',seen:[]})).json()).items.length,1);assert.equal((await(await phone(f,two.token,{type:'poll',seen:[]})).json()).items.length,0);});
test('Hermes settings and safe links apply to APK; reading never changes active alarms',async t=>{const f=fixture(t),d=await create(f);const state=JSON.parse(fs.readFileSync(f.file));state.detailOnLockScreen=true;state.categories.security=false;fs.writeFileSync(f.file,JSON.stringify(state));f.events([event(f,'denied',{category:'security'}),event(f,'task',{key:'kanban.task',url:'https://evil.test'}),event(f,'report',{key:'rhythm.2026'}),event(f,'achievement',{category:'achievements'})],0);const before=fs.readFileSync(f.feed,'utf8');const data=await(await phone(f,d.token,{type:'poll',seen:[]})).json();assert.equal(data.details,true);assert.equal(data.stale,true);assert.equal(data.items.length,3);assert.equal(data.items.find(e=>e.id==='task').url,'/modules/kanban/');assert.equal(data.items.find(e=>e.id==='report').url,'/modules/rhythm/');await phone(f,d.token,{type:'read',id:'task'});assert.equal(fs.readFileSync(f.feed,'utf8'),before);assert.equal((await phone(f,d.token,{type:'poll',seen:Array(601).fill('x')})).status,400);assert.equal((await phone(f,d.token,{type:'poll',seen:['../file']})).status,400);});
test('Hermes HTTP public endpoint requires device key while management requires login and CSRF',async t=>{
 const f=fixture(t),{createApp}=await import('../02-hub/src/server.mjs'),{passwordHash}=await import('../02-hub/src/auth.mjs');const config={username:'admin',origin:'https://hub.test',...await passwordHash('hermes-test-password')};fs.writeFileSync(f.authFile,JSON.stringify(config));const app=createApp({config,dataDirectory:path.join(f.root,'hub'),modules:new Map([['signal',{id:'signal',title:'Гермес',handle:f.handler,publicHandle:f.handler.publicHandle}]])});await new Promise(r=>app.listen(0,'127.0.0.1',r));t.after(async()=>{app.closeAllConnections();await new Promise(r=>app.close(r));});const base='http://127.0.0.1:'+app.address().port;
 assert.equal((await fetch(base+'/api/signal/phone')).status,405);assert.equal((await fetch(base+'/api/signal/phone',{method:'POST',headers:{'Content-Type':'application/json'},body:'{"type":"hello"}'})).status,401);
 const login=await fetch(base+'/api/auth/login',{method:'POST',redirect:'manual',headers:{Origin:config.origin,'Content-Type':'application/x-www-form-urlencoded'},body:'username=admin&password=hermes-test-password'});const Cookie=login.headers.get('set-cookie').split(';')[0],headers={Cookie,Origin:config.origin,'Content-Type':'application/json'};
 assert.equal((await fetch(base+'/modules/signal/phone/create',{method:'POST',headers:{...headers,Origin:'https://evil.test'},body:'{}'})).status,403);const d=await(await fetch(base+'/modules/signal/phone/create',{method:'POST',headers,body:'{}'})).json();const res=await fetch(base+'/api/signal/phone',{method:'POST',headers:{Authorization:'Bearer '+d.token,'Content-Type':'application/json'},body:'{"type":"hello"}'});assert.equal((await res.json()).state,'ready');
});
