(() => {
  const root=document.querySelector('#vpn');if(!root)return;
  const view=root.querySelector('#vpnView'),status=root.querySelector('#vpnStatus'),dialog=root.querySelector('#vpnDialog'),form=root.querySelector('#vpnForm'),fields=root.querySelector('#vpnFields');let state,tab='users',save,acting=false;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const bytes=n=>n>=1073741824?(n/1073741824).toFixed(2)+' ГиБ':n>=1048576?(n/1048576).toFixed(1)+' МиБ':n+' Б';
  const date=n=>n?new Date(n).toLocaleString('ru-RU'):'—';
  const api=async(route='',body)=>{const r=await fetch('/modules/vpn/api'+route,{method:body===undefined?'GET':'POST',cache:'no-store',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(25000)});if(r.status===401){location.replace('/login');throw Error('Нужен вход');}const value=await r.json();if(!r.ok)throw Error(value.error||'Запрос не выполнен');return value;};
  async function act(fn){if(acting)return;acting=true;status.textContent='';try{await fn();}catch(e){status.textContent=e.message;const error=fields.querySelector('#vpnFormError');if(dialog.open&&error)error.textContent=e.message;}finally{acting=false;}}
  async function refresh(){state=await api();render();}
  const button=(label,action,key='')=>`<button type="button" data-action="${action}" data-id="${esc(key)}">${label}</button>`;
  const input=(label,name,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
  const select=(label,name,options,current)=>`<label>${label}<select name="${name}">${options.map(([v,n])=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(n)}</option>`).join('')}</select></label>`;
  const countryName=code=>{const c=(state.countries??[]).find(c=>c.code===code);return c?c.flag+' '+c.name:'';};
  const countrySelect=value=>select('Страна / регион','country',[['','Не указана'],...(state.countries??[]).map(c=>[c.code,c.flag+' '+c.name])],value||'');
  const connectionName=c=>[countryName(state.nodes.find(n=>n.id===c.node)?.country),c.name].filter(Boolean).join(' · ');
  const nodeName=id=>state.agents.find(a=>a.id===id)?.name??id;
  function render(){
    for(const b of root.querySelectorAll('[data-tab]'))b.setAttribute('aria-pressed',String(b.dataset.tab===tab));
    if(tab==='users')view.innerHTML=`<div class="vpn-toolbar"><h2>Пользователи</h2>${button('Добавить','user')}</div><div class="vpn-grid">${state.users.map(u=>`<article class="vpn-card"><div class="vpn-card-head"><h3>${esc(u.name)}</h3><span>${u.active?'Активен':'Отключён / доступ истёк'}</span></div><p class="vpn-value">${bytes(u.total)} <small>/ ${u.limit?bytes(u.limit):'безлимит'}</small></p><p>${u.expires?'До '+date(u.expires):'Без срока'} · ${u.connections.length} подключений</p><div class="vpn-actions">${button('Изменить','user',u.id)}${button('Подписка','subscription',u.id)}${button(u.enabled?'Отключить':'Включить','toggle',u.id)}${button('История','history',u.id)}</div></article>`).join('')||'<p>Добавь подключение на ноде, затем создай пользователя.</p>'}</div>`;
    if(tab==='nodes')view.innerHTML=`<div class="vpn-toolbar"><h2>Серверы и подключения</h2>${button('Подключить сервер','node')}${button('Добавить подключение','connection')}</div><p>Нода устанавливается отдельным пунктом скрипта на другом VPS. Регистрация агента — в Атланте.</p><div class="vpn-grid">${state.nodes.map(n=>`<article class="vpn-card"><div class="vpn-card-head"><h3>${esc([countryName(n.country),nodeName(n.id)].filter(Boolean).join(' · '))}</h3><span>${n.agent?.revoked?'Доступ отозван':n.stale?'Нет свежих данных':n.status?.running?(n.status.revision===n.revision?'Работает':'Работает с прежними настройками'):'Остановлен'}</span></div><p>Настройки: ${n.status?.revision??0} / ${n.revision} · ${esc({applied:'Применены',pending:'Ожидается подтверждение ноды',rejected:'Отклонены',expired:'Разрешение истекло',stopped:'Остановлен',offline:'Нет свежего подтверждения',revoked:'Доступ отозван'}[n.applicationState]??'Ожидает ноду')}</p>${n.applicationState==='pending'?'<p>Новые настройки сохранены. Нода получает их автоматически; подтверждение может занять несколько десятков секунд. Подписка пока сохраняет прежнее подключение. После статуса «Применены» обнови подписку и переподключись в Happ.</p>':''}${n.applicationState==='rejected'?'<p>Новая конфигурация не принята. Причина ниже; подписка сохраняет последнее подтверждённое подключение.</p>':''}${n.status?.tls?`<p>TLS: ${n.status.tls.ready?esc(n.status.tls.names.join(', '))+' · до '+date(n.status.tls.expires):'не настроен или истёк; нужен для Hysteria 2 / Trojan'}</p>`:''}<p>Статистика: ${date(n.status?.time)}${n.status?.complete===false?' · есть незавершённый интервал учёта':''}</p>${n.status?.error?`<p role="status">${esc(n.status.error)}</p>`:''}${state.connections.filter(c=>c.node===n.id).map(c=>`<div class="vpn-connection"><div><strong>${esc(connectionName(c))}</strong><small>${esc(state.profiles[c.profile])} · ${esc(c.address)}:${c.port}${c.enabled?'':' · выключено'}</small></div>${button('Изменить','connection',c.id)}</div>`).join('')}<div class="vpn-actions">${button('Страна','country',n.id)}${button('Конфигурация','config',n.id)}</div></article>`).join('')}</div>`;
    if(tab==='routing')view.innerHTML=`<div class="vpn-toolbar"><h2>Маршрутизация</h2>${button('Создать профиль','routing')}${button('Обновить списки','refresh')}</div><p>По умолчанию — напрямую. Правила применяются в порядке списка; исключения стоят первыми. На устройстве нужен полный Xray JSON для Happ или профиль Mihomo.</p><div class="vpn-grid">${state.routing.map(r=>`<article class="vpn-card"><h3>${esc(r.name)}</h3><p>${r.rules.length} правил · ${r.groups.length} групп · ${r.sources.length} внешних списков</p><p>VPN недоступен: ${r.fallback==='direct'?'разрешён прямой выход':'VPN-направления блокируются'}</p>${button('Изменить','routing',r.id)}${r.sources.map(s=>{const d=state.sources.find(x=>x.id===s.id);return `<p class="vpn-muted">Список: ${date(d?.updated)}${d?.error?' · '+esc(d.error):''}</p>`;}).join('')}</article>`).join('')}</div>`;
    if(tab==='settings')view.innerHTML=`<article class="vpn-card"><h2>Подписки и настройки</h2><p>Панель: отдельная SQLite-база. Ноды: Xray ${esc(state.core)}. Ядро на сервере панели не устанавливается.</p><p>Персональная ссылка выдаётся в карточке пользователя. Xray JSON для Happ и профиль Mihomo переносят подключения и правила; ссылки VLESS / Trojan / Hysteria 2 переносят только подключение.</p><p>Разрешение ноды действует 2 минуты без связи с хабом. После истечения доступ закрывается. Отключение пользователя требует подтверждённого применения на нодах; при отсутствии связи — истечения разрешения.</p><p>Общий лимит распределяется порциями по нодам. Возможен перерасход за интервал измерения; незавершённый интервал при аварии отмечается как неполный. Резерв недоступной ноды не выдаётся второй раз.</p><details><summary>Совместимость и проверка</summary><p>Серверная цель: Xray ${esc(state.core)}. Основной формат: клиентский Xray JSON для Happ. Нужна версия приложения с поддержкой выбранного протокола; Hysteria 2 требует ядра с этим протоколом. Дополнительный формат: Mihomo 1.19.31 (с поддержкой XHTTP). Старые ядра и клиенты без XHTTP этот профиль не поддерживают. v2rayN / v2rayNG: отдельные URI, маршрутизация не переносится автоматически. Sing-box: полный экспорт не предлагается.</p><p>Проверка синтаксиса на ноде обязательна. Реальное соединение и импорт в конкретную версию приложения должны быть подтверждены на тестовой ноде; интерфейс не выдаёт сохранение настроек за успешное подключение.</p></details></article>`;
  }
  function modal(html,handler){fields.innerHTML=html+'<p id="vpnFormError" role="alert"></p>';save=handler;form.querySelector('[type=submit]').hidden=!handler;dialog.showModal();}
  const checks=(name,items,selected)=>`<div class="vpn-checks">${items.map(([id,label])=>`<label><input type="checkbox" name="${name}" value="${esc(id)}" ${selected.includes(id)?'checked':''}>${esc(label)}</label>`).join('')}</div>`;
  function editUser(id){const u=state.users.find(u=>u.id===id)??{name:'',enabled:true,expires:0,limit:0,connections:[]};modal(`<h2>${id?'Изменить':'Добавить'} пользователя</h2><div class="vpn-fields">${input('Имя','name',u.name,'text','required maxlength="80"')}${input('Лимит, ГиБ · 0 — безлимит','limit',u.limit/1073741824,'number','min="0" step="0.001"')}${input('Доступ до · пусто — бессрочно','expires',u.expires?new Date(u.expires-new Date(u.expires).getTimezoneOffset()*60000).toISOString().slice(0,16):'','datetime-local')}${select('Маршрутизация','routing',[['','Напрямую, без VPN-направлений'],...state.routing.map(r=>[r.id,r.name])],u.routing??'')}</div><h3>Разрешённые подключения</h3>${checks('connections',state.connections.map(c=>[c.id,nodeName(c.node)+' · '+connectionName(c)]),u.connections)}`,async d=>{await api('/user',{version:state.version,value:{...u,id,name:d.get('name'),limit:Math.round(Number(d.get('limit'))*1073741824),expires:d.get('expires')?new Date(d.get('expires')).getTime():0,routing:d.get('routing'),connections:d.getAll('connections')}});});}
  function editConnection(id){const c=state.connections.find(c=>c.id===id)??{name:'',node:state.nodes[0]?.id,profile:'vless-raw',port:443,enabled:true};modal(`<h2>Подключение</h2><div class="vpn-fields">${input('Имя','name',c.name,'text','required maxlength="80"')}${select('Нода','node',state.nodes.map(n=>[n.id,nodeName(n.id)]),c.node)}${select('Профиль','profile',Object.entries(state.profiles),c.profile)}${input('Адрес ноды','address',c.address,'text','required')}${input('Порт','port',c.port,'number','min="1" max="65535" required')}${input('SNI','sni',c.sni,'text','required')}</div><p id="vpnTransportNote" role="status"></p><label class="vpn-check"><input type="checkbox" name="enabled" ${c.enabled?'checked':''}>Включено</label><details><summary>Расширенные настройки</summary><div class="vpn-fields">${input('Reality: целевой домен','target',c.target)}${input('XHTTP: путь','path',c.path??'/nexus')}${input('gRPC: имя службы','serviceName',c.serviceName??'nexus')}${select('Fingerprint','fingerprint',['chrome','firefox','safari','randomized'].map(x=>[x,x]),c.fingerprint??'chrome')}</div><p>TLS выпускается и продлевается скриптом на ноде. SNI должен соответствовать сертификату. Ключи Reality и пароли создаются автоматически.</p></details>`,async d=>{await api('/connection',{version:state.version,value:{...c,id,...Object.fromEntries(d),enabled:d.has('enabled'),port:Number(d.get('port'))}});});
    const profile=form.elements.profile,sni=form.elements.sni,address=form.elements.address;
    const memory={reality:c.realitySni,tls:c.tlsSni};let family=profile.value.startsWith('vless')?'reality':'tls';memory[family]=sni.value;
    const update=()=>{const next=profile.value.startsWith('vless')?'reality':'tls',tls=state.nodes.find(n=>n.id===form.elements.node.value)?.status?.tls;
      if(next!==family){memory[family]=sni.value;sni.value=memory[next]||(next==='tls'?(tls?.names?.find(x=>x===address.value)||tls?.names?.[0]||address.value):(c.target||''));family=next;}
      if(next==='tls'&&tls?.ready&&!tls.names.includes(sni.value))sni.value=tls.names.find(x=>x===address.value)||tls.names[0]||sni.value;
      fields.querySelector('#vpnTransportNote').textContent=next==='tls'?(profile.value==='hysteria2'?'Hysteria 2 использует UDP. ':'')+'SNI должен быть IP или именем из сертификата этой ноды. '+(tls?.ready?'Сертификат: '+tls.names.join(', '):'Если TLS ещё не настроен, выпусти сертификат через меню VPN-ноды.'):'Reality использует SNI целевого сайта.';
      for(const name of ['target','fingerprint'])form.elements[name].closest('label').hidden=next!=='reality';
      form.elements.path.closest('label').hidden=profile.value!=='vless-xhttp';form.elements.serviceName.closest('label').hidden=profile.value!=='vless-grpc';
    };profile.addEventListener('change',update);form.elements.node.addEventListener('change',update);update();
  }
  async function subscription(id){const s=await api('/subscription?user='+id);modal(`<h2>Подписка</h2><p>Xray JSON · Happ</p><p>Импортируй эту ссылку как подписку. Подключения, DNS и правила передаются вместе. После обновления переподключись.</p><textarea readonly rows="3">${esc(s.url)}</textarea><img class="vpn-qr" src="${esc(s.qr)}" alt="QR-код персональной подписки"><div class="vpn-actions">${button('Перевыпустить ссылку','rotate',id)}${button('Заменить все ключи','rekey',id)}</div><details><summary>Другие форматы</summary><label>Mihomo<textarea readonly rows="3">${esc(s.alternatives.mihomo)}</textarea></label><label>Base64 · только подключения<textarea readonly rows="3">${esc(s.alternatives.base64)}</textarea></label></details><details><summary>Отдельные ссылки подключений</summary>${s.links.map(c=>`<label>${esc(c.name)}<textarea readonly rows="3">${esc(c.uri)}</textarea></label>`).join('')}<p>Эти ссылки не включают правила маршрутизации.</p></details>`,null);}
  function editRouting(id){const r=state.routing.find(r=>r.id===id)??{name:'',dns:'1.1.1.1',fallback:'block',rules:[],sources:[],groups:[]};const lines=r.rules.map(x=>[x.exception?'!'+x.type:x.type,x.value,x.target].join(' ')).join('\n');modal(`<h2>Маршрутизация</h2><div class="vpn-fields">${input('Имя','name',r.name,'text','required')}${input('DNS · IP','dns',r.dns,'text','required')}${select('Если VPN недоступен','fallback',[['block','Блокировать VPN-направления'],['direct','Разрешить прямой выход']],r.fallback)}</div><label>Правила · по одному на строке<textarea name="rules" rows="8" spellcheck="false" placeholder="suffix example.org vpn&#10;!domain login.example.org direct&#10;ip 203.0.113.0/24 vpn">${esc(lines)}</textarea></label><p>Формат: domain / suffix / ip, направление, цель. Цель: vpn, direct, block, ID подключения или группы. ! — исключение.</p><details><summary>Группы и внешние списки</summary><p>Группы: [{"id":"UUID","name":"Имя","connections":["ID подключения"]}]. Списки: [{"url":"https://…","type":"suffix","target":"vpn","exception":false}]. Источник — текст, одна запись на строку.</p><label>Группы JSON<textarea name="groups" rows="4" spellcheck="false">${esc(JSON.stringify(r.groups,null,2))}</textarea></label><label>Списки JSON<textarea name="sources" rows="4" spellcheck="false">${esc(JSON.stringify(r.sources,null,2))}</textarea></label><p>Подключения: ${state.connections.map(c=>esc(c.name)+': '+esc(c.id)).join('<br>')}</p></details>`,async d=>{const rules=d.get('rules').split(/\r?\n/).map(s=>s.trim()).filter(Boolean).map(line=>{const [type,value,target,...extra]=line.split(/\s+/);if(extra.length||!target)throw Error('Неверная строка правила');return {type:type.replace(/^!/,''),value,target,exception:type.startsWith('!')};});await api('/routing',{version:state.version,value:{...r,id,name:d.get('name'),dns:d.get('dns'),fallback:d.get('fallback'),rules,groups:JSON.parse(d.get('groups')),sources:JSON.parse(d.get('sources'))}});});}
  async function action(action,id){
    if(action==='user')return editUser(id||undefined);if(action==='connection')return editConnection(id||undefined);if(action==='routing')return editRouting(id||undefined);if(action==='subscription')return subscription(id);
    if(action==='country'){const n=state.nodes.find(n=>n.id===id);return modal(`<h2>Страна сервера</h2><p>${esc(nodeName(id))}</p>${countrySelect(n?.country)}<p>Флаг и страна появятся у всех подключений этого сервера в подписках. В Happ обнови подписку. Перезапуск VPN не требуется.</p>`,async d=>{await api('/node-country',{id,country:d.get('country'),version:state.version});return 'Страна сохранена. Названия в подписке обновлены; обнови подписку в Happ.';});}
    if(action==='node')return modal(`<h2>Подключить сервер</h2>${select('Зарегистрированный агент','node',state.agents.filter(a=>!a.revoked).map(a=>[a.id,a.name]),'')}${countrySelect('')}<p>На этом VPS должен быть выполнен отдельный пункт «VPN-нода». Обычный агент не запускает VPN сам.</p>`,async d=>{await api('/node',{id:d.get('node'),settings:{},country:d.get('country'),version:state.version});});
    if(action==='toggle'){const u=state.users.find(u=>u.id===id);if(!await Nexus.confirm(`${u.enabled?'Отключить':'Включить'} доступ «${u.name}»?`))return;await api('/user',{version:state.version,value:{...u,enabled:!u.enabled}});await refresh();}
    if(action==='rotate'||action==='rekey'){if(!await Nexus.confirm(action==='rotate'?'Перевыпустить ссылку? Уже импортированные ключи продолжат работать.':'Заменить ссылку и все ключи? Старые подключения перестанут работать после применения на нодах.'))return;await api('/rotate',{id,version:state.version,credentials:action==='rekey'});dialog.close();await refresh();await subscription(id);}
    if(action==='refresh'){await api('/refresh',{});await refresh();status.textContent='Списки проверены. Клиенты получат изменения при обновлении подписки.';}
    if(action==='history'){const u=state.users.find(u=>u.id===id),h=await api('/history?user='+id);modal(`<h2>${esc(u.name)} · расход</h2>${u.nodes.map(n=>`<p>${esc(nodeName(n.node))}: ↑ ${bytes(n.up)} · ↓ ${bytes(n.down)}</p>`).join('')}<div class="vpn-history">${h.rows.map(r=>`<div>${date(r.hour*3600000)} · ${esc(nodeName(r.node))}<strong>${bytes(r.up+r.down)}</strong></div>`).join('')||'Пока нет измерений'}</div>`,null);}
    if(action==='config'){const c=await api('/config?node='+id);modal(`<h2>Конфигурация ноды</h2><p>${esc(c.notice)}</p><label>Итоговая конфигурация · содержит секреты<textarea name="config" rows="20" spellcheck="false">${esc(JSON.stringify(c.config,null,2))}</textarea></label>`,async d=>{await api('/config',{id,config:JSON.parse(d.get('config')),version:state.version});});}
  }
  root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab){tab=b.dataset.tab;render();}if(b.dataset.action)void act(()=>action(b.dataset.action,b.dataset.id));});
  root.querySelector('#vpnCancel').onclick=()=>dialog.close();form.onsubmit=e=>{e.preventDefault();void act(async()=>{const message=await save?.(new FormData(form));dialog.close();await refresh();status.textContent=message||'Сохранено. Дождись «Применены» в разделе серверов, затем обнови подписку и переподключись в Happ.';});};
  window.Nexus?.beforeLeave?.(async()=>!acting&&(!dialog.open||await Nexus.confirm('Закрыть настройки Арго?')));
  void act(refresh);const poll=setInterval(()=>{if(!document.hidden&&!acting&&!dialog.open)void act(refresh);},3000);window.addEventListener('pagehide',()=>clearInterval(poll),{once:true});
})();
